google: ''
openai:
  required: ["base-url", "api-key", "model"]
  rpm: 60
glm:
  type: openai
  max-concurrency: 100
  req-args:
    thinking:
      type: disabled
siliconflow:
  type: openai
  rpm: 300
  req-args:
    enable_thinking: false
